package com.linric.psycalc;

/**
 * Created by jbueno on 4/1/2018.
 */
public class AppConstants {

    static final String DEFAULT_INPUT_MEASUREMENT_SYSTEM = "DEFAULT_INPUT_MEASUREMENT_SYSTEM";
    static final String DEFAULT_OUTPUT_MEASUREMENT_SYSTEM = "DEFAULT_OUTPUT_MEASUREMENT_SYSTEM";
    static final String DEFAULT_INPUT_ONE_FIELD_CHOICE = "DEFAULT_INPUT_ONE_FIELD_CHOICE";
    static final String DEFAULT_INPUT_TWO_FIELD_CHOICE = "DEFAULT_INPUT_TWO_FIELD_CHOICE";
    static final String DEFAULT_INPUT_FLOW_FIELD_CHOICE = "DEFAULT_INPUT_FLOW_FIELD_CHOICE";
    static final String DEFAULT_ALTITUDE_FIELD_CHOICE = "DEFAULT_ALTITUDE_FIELD_CHOICE";

}
